<a href="https://colab.research.google.com/github/LCaravaggio/EscueladeInnovacion/blob/main/Tabla_Interactiva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tabla Interactiva

In [1]:
from vega_datasets import data

In [2]:
cars=data.cars()
cars

,Name,Miles_per_Gallon,Cylinders,Displacement,Horsepower,Weight_in_lbs,Acceleration,Year,Origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,1970-01-01,USA
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,1970-01-01,USA
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,1970-01-01,USA
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,1970-01-01,USA
4,ford torino,17.0,8,302.0,140.0,3449,10.5,1970-01-01,USA
...,...,...,...,...,...,...,...,...,...
401,ford mustang gl,27.0,4,140.0,86.0,2790,15.6,1982-01-01,USA
402,vw pickup,44.0,4,97.0,52.0,2130,24.6,1982-01-01,Europe
403,dodge rampage,32.0,4,135.0,84.0,2295,11.6,1982-01-01,USA
404,ford ranger,28.0,4,120.0,79.0,2625,18.6,1982-01-01,USA
405,chevy s-10,31.0,4,119.0,82.0,2720,19.4,1982-01-01,USA

# SQL

In [7]:
import sqlite3

database_path = 'cars.db'
con = sqlite3.connect(database_path)

# Convierto el DF a una base de SQL
cars.to_sql('cars_table', con, if_exists='replace', index=False)

# Y listo, puedo ejecutar instrucciones
cur = con.cursor()
cur.execute("SELECT * FROM cars_table WHERE Miles_per_Gallon > 40")
rows = cur.fetchall()

for row in rows:
    print(row)

# Cierro la conexión
con.close()

('volkswagen rabbit custom diesel', 43.1, 4, 90.0, 48.0, 1985, 21.5, '1978-01-01 00:00:00', 'Europe')
('vw rabbit', 41.5, 4, 98.0, 76.0, 2144, 14.7, '1980-01-01 00:00:00', 'Europe')
('mazda glc', 46.6, 4, 86.0, 65.0, 2110, 17.9, '1980-01-01 00:00:00', 'Japan')
('datsun 210', 40.8, 4, 85.0, 65.0, 2110, 19.2, '1980-01-01 00:00:00', 'Japan')
('vw rabbit c (diesel)', 44.3, 4, 90.0, 48.0, 2085, 21.7, '1980-01-01 00:00:00', 'Europe')
('vw dasher (diesel)', 43.4, 4, 90.0, 48.0, 2335, 23.7, '1980-01-01 00:00:00', 'Europe')
('honda civic 1500 gl', 44.6, 4, 91.0, 67.0, 1850, 13.8, '1980-01-01 00:00:00', 'Japan')
('renault lecar deluxe', 40.9, 4, 85.0, None, 1835, 17.3, '1980-01-01 00:00:00', 'Europe')
('vw pickup', 44.0, 4, 97.0, 52.0, 2130, 24.6, '1982-01-01 00:00:00', 'Europe')